spring:
  application:
    name: ImoocMerchants
  datasource:
    url: jdbc:mysql://192.168.31.3:3306/passbook?autoReconnect=true
    username: root
    password: 123456
  kafka:
    bootstrap-servers: 192.168.31.3:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527

logging:
  level: debug
  file: imooc-merchants.log
